// danh sách các mệnh đề đúng lớp 10, học kỳ 1: (SGK Chân Trời Sáng Tạo)
const menhDeDung = [
    ` 12 < ${mathString(`\\sqrt{169}`)}.`,
    ` ${mathString(`5^2 + 12^2 = 13^2`)}.`,
    ` ${mathString(` \\sqrt{3}-1 < 2`)}.`,
    ` ${mathString(` (x-2)^2 = x^2 -4x + 4`)}.`,
    ` ${mathString(`\\dfrac{1}{1-\\sqrt{2}} = -1-\\sqrt{2}`)}.`,
    ` ${mathString(` 3^2 + 4^2 = 5^2`)}`,
    ` 5 là ước của 10.`,
    ` 2 là ước của 10.`,
    ` 9 chia hết cho 3.`,
    ` 16 chia hết cho 2.`,
    ` 91 không là số nguyên tố.`,
    ` 17 là số nguyên tố.`,
    ` 7 là số nguyên tố.`,
    ` 31 là số nguyên tố.`,
    ` ${mathString(`\\frac{2}{3}`)} là số hữu tỉ.`,
    ` ${mathString(`\\sqrt{7}`)} là số vô tỉ.`,
    ` ${mathString(`\\sqrt{4}`)} là số hữu tỉ.`,
    ` 16 là hợp số.`,
    ` 9 là hợp số.`,
    ` 25 là số chính phương.`,
    ` Các số 1, 3, 5  và 7 đều là ước của 315.`,
    ` 12 là ước của ${mathString(`100-4`)}.`,
    ` Tam thức bậc hai ${mathString(`ax^2+bx+c`)} có nghiệm kép khi ${mathString(`\\Delta =0`)}.`,
    ` Tam thức bậc hai ${mathString(`ax^2+bx+c`)} có 2 nghiệm phân biệt khi ${mathString(`\\Delta > 0`)}.`,
    ` Biệt thức của tam thức bậc hai: ${mathString(`ax^2 + bx + c`)} tính bởi công thức ${mathString(`\\Delta = b^2 - 4ac`)}.`,
    ` Đồ thị hàm số ${mathString(`y=ax^2`)} luôn đi qua gốc tọa độ.`,
    ` Đồ thị hàm số ${mathString(`y=ax^2`)} là đường Parabol.`,
    ` Phương trình ${mathString(`2x^2 -3x + 1 = 0`)} có 2 nghiệm phân biệt.`,
    ` Tứ giác nội tiếp có tổng 2 góc đối bằng ${mathString(`180^o`)}.`,
    ` Mọi tam giác đều nội tiếp một đường tròn nào đó.`,
    ` Diện tích hình tròn bán kính R là ${mathString(`S = \\pi R^2`)}.`,
    ` Chu vi hình tròn bán kính R là ${mathString(`P = 2\\pi R`)}.`,
    ` TỔng 4 góc của một tứ giác nội tiếp bằng ${mathString(`360^o`)}.`,
    ` Độ dài cung tròn có số đo ${mathString(`\\alpha^o`)} và bán kính R bằng ${mathString(`l = \\frac{\\pi R^2 \\alpha}{360}`)}.`,
    ` Với A và B không âm, ta luôn có ${mathString(`\\frac{\\sqrt{A}}{\\sqrt{B}} = \\sqrt{\\frac{A}{B}}`)}.`,
    ` Số 2 có đúng hai căn bậc hai.`,
    ` Số 2 có đúng một căn bậc 3. `,
    ` Lượng liên hiệp của ${mathString(`1-\\sqrt{2}`)} là ${mathString(`1+\\sqrt{2}`)}.`,
    ` ${mathString(`\\sqrt{3}-5`)} có lượng liên hiệp là ${mathString(`\\sqrt{3}+5`)}.`,
    ` Có đúng 2 số thực mà bình phương của chúng đều bằng 5.`,
    ` Có đúng 2 nguyên nguyên mà bình phương của chúng là 9.`,
    ` Bất phương trình ${mathString(`x^2 - 3x > 4`)} thỏa khi cho ${mathString(`x= -2`)}.`,
    ` Có đúng 2 số nguyên a thỏa ${mathString(`a^2-a < 1`)}.`,
    ` Với ${mathString(`a=1`)} thì bất phương trình ${mathString(`a^2-a < 1`)} đúng.`,
    ` Trong tam giác ABC vuông tại A, tỉ số ${mathString(`\\frac{AB}{BC}`)} gọi là ${mathString(`\\sin`)} của góc ${mathString(`\\hat{C}`)}.`,
    ` Trong tam giác vuông, tỉ số độ dài 2 cạnh góc vuông gọi là ${mathString(`\\tan`)} hoặc ${mathString(`\\cot`)} của góc tương ứng.`,
    ` Góc nội tiếp một đường tròn có số đo bằng nửa số đo cung bị chắn.`,
    ` Trong một bảng dữ liệu ghép nhóm, giá trị đại diện cho nhóm ${mathString(`(12,14]`)} là ${mathString(`13`)}.`,
    ` Việt Nam từ ngày 01/7/2025 có 34 tỉnh/thành phố.`,
    ` Cá voi không phải thuộc lớp cá.`,
    ` Hải cẩu là loài động vật máu nóng.`,
    ` Cá heo thở bằng phổi và chúng có khả năng lặng rất lâu dưới nước.`,
    ` Lúa là thực vật 1 lá mầm.`,
    ` Chanh là loài thực vật 2 lá mầm.`,
    ` Sau quá trình nguyên phân, mỗi tế bào sinh ra 2 tế bào con.`
]

// danh sách các mệnh đề sai lớp 10, học kỳ 1: (SGK Chân Trời Sáng Tạo)
const menhDeSai = [
    ` ${mathString(` -3 > -1`)}.`,
    ` ${mathString(` \\frac{3}{\\sqrt{2}}  = \\frac{2\\sqrt{2}}{2}`)}`,
    ` ${mathString(` (x+1)^2 = x^2 - 2x +1 `)}.`,
    ` 5 là bội của 3.`,
    ` 2 là ước của 9.`,
    ` 99 chia hết cho 6.`,
    ` 16 chia hết cho 6.`,
    ` 91 không số nguyên tố.`,
    ` 17 là hợp số.`,
    ` 7 là hợp số.`,
    ` 30 là số nguyên tố.`,
    ` ${mathString(`\\frac{2}{3}`)} là số vô tỉ.`,
    ` ${mathString(`\\sqrt{7}`)} là số hữu tỉ.`,
    ` ${mathString(`\\sqrt{4}`)} là số vô tỉ.`,
    ` 16 là số nguyên tố.`,
    ` 9 là số nguyên tố.`,
    ` 25 là số vô tỉ.`,
    ` Các số 3, 5  và 17 đều là ước của 315.`,
    ` 12 là ước của 38.`,
    ` Tam thức bậc hai ${mathString(`ax^2+bx+c`)} có nghiệm kép khi ${mathString(`\\Delta < 0`)}.`,
    ` Tam thức bậc hai ${mathString(`ax^2+bx+c`)} có 2 nghiệm phân biệt khi ${mathString(`\\Delta \\geq 0`)}.`,
    ` Biệt thức của tam thức bậc hai: ${mathString(`ax^2 + bx + c`)} tính bởi công thức ${mathString(`\\Delta = b^2 + 4ac`)}.`,
    ` Đồ thị hàm số ${mathString(`y=ax^2`)} luôn đi qua điểm có tọa độ ${mathString(`(1,1)`)}.`,
    ` Đồ thị hàm số ${mathString(`y=ax^2`)} là đường thẳng.`,
    ` Phương trình ${mathString(`2x^2 -3x + 1 = 0`)} có nghiệm kép.`,
    ` Tứ giác nội tiếp có tổng 4 góc bằng ${mathString(`180^o`)}.`,
    ` Mọi tứ giác bất kỳ đều nội tiếp một đường tròn nào đó.`,
    ` Diện tích hình tròn bán kính R là ${mathString(`S = 2 \\pi R^2`)}.`,
    ` Chu vi hình tròn bán kính R là ${mathString(`P = \\pi R^2`)}.`,
    ` Tổng 2 góc đối của một tứ giác nội tiếp bằng ${mathString(`360^o`)}.`,
    ` Độ dài cung tròn có số đo ${mathString(`\\alpha^o`)} và bán kính R bằng ${mathString(`l = \\frac{\\pi R^2 \\alpha}{360}`)}.`,
    ` Với A và B không âm, ta luôn có ${mathString(`\\frac{\\sqrt{A}}{\\sqrt{B}} = \\frac{\\sqrt{A}}{B}`)}.`,
    ` Số 2 có một căn bậc hai.`,
    ` Số 2 có đúng hai căn bậc 3. `,
    ` Lượng liên hiệp của ${mathString(`1-\\sqrt{2}`)} là ${mathString(`\\sqrt{2}-1`)}.`,
    ` ${mathString(`\\sqrt{3}-5`)} có lượng liên hiệp là ${mathString(`-\\sqrt{3}+5`)}.`,
    ` Có vô số số thực mà bình phương của chúng bằng 5.`,
    ` Có đúng 2 số nguyên mà bình phương của chúng bằng 7.`,
    ` Có đúng 1 số nguyên a thỏa ${mathString(`a^2-a < 1`)}.`,
    ` Với ${mathString(`a=-1`)} thì bất phương trình ${mathString(`a^2-a < 1`)} đúng.`,
    ` Phương trình ${mathString(`-2x^2 - 3x + 5 = 0`)} có nghiệm là ${mathString(`x=-1`)}.`,
    ` Trong tam giác ABC vuông tại A, tỉ số ${mathString(`\\frac{AB}{BC}`)} gọi là ${mathString(`\\cos`)} của góc ${mathString(`\\hat{C}`)}.`,
    ` Trong tam giác vuông, tỉ số độ dài 2 cạnh góc vuông gọi là ${mathString(`\\sin`)} hoặc ${mathString(`\\cos`)} của góc tương ứng.`,
    ` Góc nội tiếp một đường tròn có số đo bằng số đo cung bị chắn.`,
    ` Torng một bảng dữ liệu ghép nhóm, giá trị đại diện cho nhóm ${mathString(`(12,14]`)} là ${mathString(`14`)}.`,
    ` Việt Nam từ ngày 01/7/2025 có 43 tỉnh/thành phố.`,
    ` Cá voi thuộc lớp lưỡng cư.`,
    ` Cóc là động vật thân mềm.`,
    ` Hải cẩu là loài động vật máu lạnh.`,
    ` Cá heo thở bằng mang.`,
    ` Lúa là thực vật 2 lá mầm.`,
    ` Chanh là loài thực vật 1 lá mầm.`,
    ` Cây hành lá có bộ rễ cọc.`,
    ` Sau quá trình giảm phân, mỗi tế bào sinh ra 2 tế bào con.`
]

// danh sách câu không phải mệnh đề, không phải mệnh đề chứa biến:
const cauNoi = [
    `Trời nóng quá!`,
    `Có bao nhiêu số tự nhiên chia hết cho 3?`,
    `Cá heo nhảy lên khỏi mặt nước.`,
    `Hoa này không hợp với tôi.`,
    `Có bao nhiêu thứ phải làm!`,
    `Đề bài khó quá.`,
    `Hoa hướng dương rất to.`,
    `Ai xả rác ở đây?`,
    `Hết rồi.`,
    `Mệt!`,
    `Có ai ở đây không?`,
    `Phương trình ${mathString(`x^2 -3x + 1= 0`)} có bao nhiêu nghiệm?`,
    `Mưa to quá, ngập hết rồi!`,
    `Còn nhiều phát biểu chưa chính xác.`,
    `Bữa nay lạnh quá!`,
    `Tìm số nguyên mà bình phương bằng 9.`,
    `Nếu x là số hữu tỉ.`,
    `Có một con mèo ngồi bên cửa sổ.`
]

// danh sách mệnh đề chứa biến.
const menhDeChuaBien = [
    ` x là số nguyên.`,
    ` a là số hữu tỉ.`,
    ` ${mathString(`\\tan{A} > 1`)}.`,
    ` m là số vô tỉ.`,
    ` x thỏa ${mathString(`x^2 - 3x + 2 < 1`)}.`,
    ` ${mathString(`x^2 - 3x < 3`)}.`,
    ` x chia hết cho 3.`,
    ` x chia hết cho 4.`,
    ` x chia hết cho 9.`,
    ` x không chia hết cho 12.`,
]